apiVersion: v1
kind: Service
metadata:
  name: pensamiento-computacional
  labels:
    app: pensamiento-computacional
spec:
  selector:
    app: pensamiento-computacional
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
